# Generated by Django 3.2.6 on 2021-09-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_djongo', '0005_alter_book_book_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_money',
            field=models.IntegerField(default=100),
        ),
    ]
