# Generated by Django 3.2.6 on 2021-09-01 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Author_Info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=40)),
                ('author_emaill', models.EmailField(max_length=254)),
                ('author_gender', models.CharField(choices=[('0', '女性'), ('1', '男性'), ('2', '保密')], max_length=10)),
            ],
            options={
                'db_table': 'tb_author_info',
            },
        ),
        migrations.CreateModel(
            name='Book_Publish_Info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('publish_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hoot_book', models.BooleanField()),
                ('book_name', models.CharField(max_length=40)),
                ('book_info', models.TextField()),
                ('book_date', models.DateField()),
                ('book_author', models.ManyToManyField(db_table='tb_book_author_many', to='test_djongo.Book_Author_Info')),
                ('book_publish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_djongo.book_publish_info')),
            ],
            options={
                'db_table': 'tb_book',
            },
        ),
    ]
