# Generated by Django 3.2.6 on 2021-09-01 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_djongo', '0002_auto_20210901_0814'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book_author_emaill',
            table='tb_author_emaill',
        ),
        migrations.AlterModelTable(
            name='book_publish_info',
            table='tb_publish',
        ),
    ]
