# Generated by Django 3.2.6 on 2021-09-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_djongo', '0003_auto_20210901_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='hoot_book',
            field=models.BooleanField(default=1, null=True),
        ),
    ]
