# Generated by Django 3.2.6 on 2021-09-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_djongo', '0004_auto_20210901_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
